
package ui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class ClientesFrame extends javax.swing.JFrame {

    private final List<Cliente> data = new ArrayList<>();
    private DefaultTableModel model;
    private Integer filaSeleccionada = null;

    public ClientesFrame() {
        initComponents();
        setTitle("Gestión de Clientes");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        // Configuración del modelo de tabla
        model = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Apellido", "DNI", "Dirección", "Teléfono"}, 0
        ) {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        tblClientes.setModel(model);
        tblClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Eventos de los botones
        btnNuevo.addActionListener(e -> limpiarFormulario());
        btnGuardar.addActionListener(e -> guardarCliente());
        btnEliminar.addActionListener(e -> eliminarSeleccionado());

        // Evento de selección en la tabla
        tblClientes.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = tblClientes.getSelectedRow();
                if (fila >= 0) {
                    filaSeleccionada = fila;
                    cargarFormularioDesdeFila(fila);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesFrame().setVisible(true);
            }
        });
    }
    // ---------------- Métodos auxiliares ----------------
private void guardarCliente() {
    if (txtNombre.getText().isBlank() || txtDni.getText().isBlank()) {
        JOptionPane.showMessageDialog(this, "Nombre y DNI son obligatorios.");
        return;
    }

    if (filaSeleccionada == null) {
        Cliente c = new Cliente(
                nextId(),
                txtNombre.getText(),
                txtApellido.getText(),
                txtDni.getText(),
                txtDireccion.getText(),
                txtTelefono.getText()
        );
        data.add(c);
    } else {
        Cliente c = data.get(filaSeleccionada);
        c.nombre = txtNombre.getText();
        c.apellido = txtApellido.getText();
        c.dni = txtDni.getText();
        c.direccion = txtDireccion.getText();
        c.telefono = txtTelefono.getText();
    }
    refrescarTabla();
    limpiarFormulario();
}

    private void eliminarSeleccionado() {
        int fila = tblClientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
            return;
        }
        int op = JOptionPane.showConfirmDialog(this, "¿Eliminar cliente?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            data.remove(fila);
            refrescarTabla();
            limpiarFormulario();
        }
    }

    private void refrescarTabla() {
        model.setRowCount(0);
        for (Cliente c : data) {
            model.addRow(new Object[]{c.id, c.nombre, c.apellido, c.dni, c.direccion, c.telefono});
        }
    }

    private void limpiarFormulario() {
        filaSeleccionada = null;
        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        tblClientes.clearSelection();
    }

    private void cargarFormularioDesdeFila(int fila) {
        Cliente c = data.get(fila);
        txtNombre.setText(c.nombre);
        txtApellido.setText(c.apellido);
        txtDni.setText(c.dni);
        txtDireccion.setText(c.direccion);
        txtTelefono.setText(c.telefono);
    }

    private long nextId() {
        long max = 0;
        for (Cliente c : data) if (c.id > max) max = c.id;
        return max + 1;
    }

    private void seed() {
        data.add(new Cliente(1, "Ana", "Gómez", "30111222", "Calle 1", "11223344"));
        data.add(new Cliente(2, "Luis", "Pérez", "30222333", "Calle 2", "22334455"));
    }

    // Clase interna simple
    private static class Cliente {
        long id;
        String nombre, apellido, dni, direccion, telefono;
        Cliente(long id, String n, String a, String d, String dir, String tel) {
            this.id = id;
            this.nombre = n;
            this.apellido = a;
            this.dni = d;
            this.direccion = dir;
            this.telefono = tel;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
